// ─────────────────────────────────────────────────────────────────────────────
// pages/Recommendations.jsx — Personalised "For You" page
//
// Shows the movies predicted to be the best match for the current user,
// generated by the collaborative filtering algorithm on the backend.
//
// Empty state: if the user hasn't rated enough movies yet, the algorithm
// falls back to top-rated movies and the backend may return fewer results.
// We prompt the user to browse and rate more movies.
// ─────────────────────────────────────────────────────────────────────────────

import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getRecommendations } from '../services/api';
import { useAuth } from '../hooks/useAuth';
import MovieCard from '../components/MovieCard';
import './Recommendations.css';

export default function Recommendations() {
  const { user }               = useAuth();
  const navigate               = useNavigate();
  const [recs,    setRecs]     = useState([]);   // The list of recommended movies
  const [loading, setLoading]  = useState(true);

  useEffect(() => {
    // Redirect to login if not authenticated (belt-and-suspenders: App.jsx
    // already wraps this route in <ProtectedRoute>)
    if (!user) { navigate('/auth'); return; }

    getRecommendations()
      .then(({ data }) => setRecs(data))
      .catch(() => {}) // Fail silently — empty state is handled below
      .finally(() => setLoading(false));
  }, [user, navigate]);

  if (loading) return <div className="recs"><div className="spinner" /></div>;

  return (
    <div className="recs fade-in">
      <div className="recs__inner">

        {/* Page header */}
        <div className="recs__header">
          <h1 className="recs__title">
            For You
            <span className="recs__badge">AI Picks</span>
          </h1>
          <p className="recs__sub">
            Personalized picks based on your ratings and users with similar taste.
          </p>
        </div>

        {/* Empty state — shown when the algorithm didn't produce any results */}
        {recs.length === 0 ? (
          <div className="recs__empty">
            <div className="recs__empty-icon">🎬</div>
            <h3>Not enough data yet</h3>
            <p>Rate at least 5 movies and we'll generate your personalized picks.</p>
            <button className="recs__cta" onClick={() => navigate('/')}>
              Browse Movies →
            </button>
          </div>
        ) : (
          /* Grid layout of MovieCard components */
          <div className="recs__grid">
            {recs.map((movie) => (
              <MovieCard key={movie.omdb_id || movie.id} movie={movie} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
